#!/usr/bin/env python3
"""gen-rooms.py — generate rooms.md, a drift-proof existence index of a repo's rooms.

A "room" is any directory under the repo that contains a CLAUDE.md. This walks
<repo>/**/CLAUDE.md, extracts each room's path (relative to the repo) and a
one-line description (the first prose sentence beneath the H1), and writes a
flat, alphabetically sorted rooms.md at the repo root. Regenerable from the
tree, so it cannot drift: add or remove a room and the next run reflects it.

Generic across any multi-room repo (not notes-specific). The OUTPUT (rooms.md)
is committed in the target repo; this GENERATOR lives in the toolkit, per the
markdown-only / lozuko boundary (bon-walile, under bon-gopewu).

Stdlib only, plain python3 (no uv): it is invoked from the close-time path,
where uv's per-invocation latency would not pay for itself and there are no
third-party deps to manage.

Integrity: a room whose CLAUDE.md is *ignored* by git can never be tracked or
synced — it exists only on the machine that wrote it, while rooms.md (built
from the filesystem) advertises it everywhere (notes-laninu: a bare `mise/`
pattern hid `practices/mise/` for a month). Such rooms are flagged inline in
rooms.md, naming the culprit ignore line. Merely-untracked rooms (minted but
not yet committed) are routine and not flagged. Non-git directories skip the
check.

Usage:
  gen-rooms.py [REPO_DIR]            write rooms.md (REPO_DIR defaults to cwd)
  gen-rooms.py --check [REPO_DIR]    exit 1 if rooms.md is missing or stale,
                                     or if any listed room is git-ignored
                                     (writes nothing) — for CI / pre-commit
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

MARKER = "<!-- generated by gen-rooms.py — do not edit; regenerated on close/commit (bon-walile) -->"
SKIP_DIRS = {".git", ".bon", "node_modules", ".venv", "__pycache__"}


def first_sentence(text: str) -> str:
    """First sentence of a prose line — cut at the first '. ' boundary."""
    text = text.strip()
    idx = text.find(". ")
    if idx != -1:
        return text[: idx + 1]
    return text


def describe(claude_md: Path) -> str:
    """The room's one-liner: first prose line under the H1, as a single sentence.

    Falls back to the H1 heading text, then to '(no description)'.
    """
    heading = ""
    for raw in claude_md.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            if not heading:
                heading = line.lstrip("#").strip()
            continue
        if line.startswith((">", "<!--", "|", "---")):
            continue  # blockquote / status banner / HTML comment / table / rule
        return first_sentence(line)
    return heading or "(no description)"


def find_rooms(repo: Path) -> list[tuple[str, str]]:
    """Every sub-room (dir with a CLAUDE.md), as (relative-path, one-liner).

    The repo-root CLAUDE.md is skipped — it is the orientation doc that hosts
    this index, not a room within it.
    """
    rooms: list[tuple[str, str]] = []
    for claude_md in repo.rglob("CLAUDE.md"):
        rel_parts = claude_md.relative_to(repo).parts
        if any(part in SKIP_DIRS for part in rel_parts):
            continue
        room_dir = claude_md.parent
        if room_dir == repo:
            continue  # repo root — not a sub-room
        rel = room_dir.relative_to(repo).as_posix() + "/"
        rooms.append((rel, describe(claude_md)))
    rooms.sort(key=lambda r: r[0])
    return rooms


def ignored_room_notes(repo: Path, rooms: list[tuple[str, str]]) -> dict[str, str]:
    """Rooms whose CLAUDE.md git *ignores*, mapped to the culprit ignore line.

    Ignored — not merely untracked — is the pathology: an ignored room can
    never be committed or synced, so it silently exists on one machine only
    while rooms.md advertises it on all of them. A just-minted room awaiting
    its first commit is untracked but not ignored, and is not flagged. A
    tracked CLAUDE.md that happens to match an ignore pattern (force-added)
    is visible to git and is not flagged either. Returns {} outside a git
    work tree or when git is unavailable.
    """
    paths = [rel + "CLAUDE.md" for rel, _ in rooms]
    if not paths:
        return {}
    try:
        tracked = subprocess.run(
            ["git", "-C", str(repo), "ls-files", "-z", "--", *paths],
            capture_output=True, text=True, timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return {}
    if tracked.returncode != 0:
        return {}  # not a git work tree — nothing to assert
    tracked_set = set(tracked.stdout.split("\0"))
    untracked = [p for p in paths if p not in tracked_set]
    if not untracked:
        return {}
    try:
        # -z demands --stdin (fatal otherwise); with both, input and output
        # are NUL-separated, which keeps rooms with spaces in their names safe.
        check = subprocess.run(
            ["git", "-C", str(repo), "check-ignore", "-v", "-z", "--stdin"],
            input="\0".join(untracked) + "\0",
            capture_output=True, text=True, timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return {}
    # -z output: <source> NUL <linenum> NUL <pattern> NUL <pathname> NUL …
    notes: dict[str, str] = {}
    fields = check.stdout.split("\0")
    for i in range(0, len(fields) - 3, 4):
        source, linenum, pattern, pathname = fields[i : i + 4]
        if pattern.startswith("!"):
            continue  # deciding pattern is a negation — the path is NOT ignored
        rel_room = pathname[: -len("CLAUDE.md")]
        notes[rel_room] = f"`{source}:{linenum} {pattern}`"
    return notes


def render(repo: Path) -> str:
    rooms = find_rooms(repo)
    notes = ignored_room_notes(repo, rooms)
    lines = [
        MARKER,
        "# Rooms",
        "",
        "An existence index of every room (a directory with a `CLAUDE.md`) in "
        "this repo. Generated — do not hand-edit.",
        "",
    ]
    if rooms:
        for rel, desc in rooms:
            line = f"- [`{rel}`]({rel}CLAUDE.md) — {desc}"
            if rel in notes:
                line += (
                    f" ⚠️ **IGNORED by {notes[rel]} — git cannot see this room; "
                    "it exists only on the machine that wrote it until that "
                    "ignore line is fixed**"
                )
            lines.append(line)
    else:
        lines.append("_No sub-rooms found._")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    check = False
    args = [a for a in argv if a != "--check"]
    if "--check" in argv:
        check = True
    repo = Path(args[0]) if args else Path.cwd()
    repo = repo.resolve()
    if not repo.is_dir():
        print(f"gen-rooms: not a directory: {repo}", file=sys.stderr)
        return 2

    new = render(repo)
    out = repo / "rooms.md"
    current = out.read_text(encoding="utf-8") if out.exists() else None
    has_ignored = "⚠️ **IGNORED by" in new

    if check:
        if current != new:
            print(f"gen-rooms: {out} is stale or missing", file=sys.stderr)
            return 1
        if has_ignored:
            print(
                "gen-rooms: rooms.md lists git-ignored room(s) — see the "
                "⚠️ IGNORED annotations",
                file=sys.stderr,
            )
            return 1
        return 0

    if has_ignored:
        # Non-fatal on the write path (close must not abort), but say it —
        # the inline annotation in rooms.md is the durable half of the alarm.
        print(
            "gen-rooms: WARNING — git-ignored room(s) flagged in rooms.md",
            file=sys.stderr,
        )
    if current == new:
        return 0  # no change — leave mtime untouched so nothing churns
    out.write_text(new, encoding="utf-8")
    print(f"gen-rooms: wrote {out} ({new.count(chr(10) + '- ')} rooms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
