#!/usr/bin/env python3
"""gen-rooms.py — generate rooms.md, a drift-proof existence index of a repo's rooms.

A "room" is any directory under the repo that contains a CLAUDE.md. This walks
<repo>/**/CLAUDE.md, extracts each room's path (relative to the repo) and a
one-line description (the first prose sentence beneath the H1), and writes a
flat, alphabetically sorted rooms.md at the repo root. Regenerable from the
tree, so it cannot drift: add or remove a room and the next run reflects it.

Generic across any multi-room repo (not notes-specific). The OUTPUT (rooms.md)
is committed in the target repo; this GENERATOR lives in the toolkit, per the
markdown-only / lozuko boundary (bon-walile, under bon-gopewu).

Stdlib only, plain python3 (no uv): it is invoked from the close-time path,
where uv's per-invocation latency would not pay for itself and there are no
third-party deps to manage.

Usage:
  gen-rooms.py [REPO_DIR]            write rooms.md (REPO_DIR defaults to cwd)
  gen-rooms.py --check [REPO_DIR]    exit 1 if rooms.md is missing or stale
                                     (writes nothing) — for CI / pre-commit
"""
from __future__ import annotations

import sys
from pathlib import Path

MARKER = "<!-- generated by gen-rooms.py — do not edit; regenerated on close/commit (bon-walile) -->"
SKIP_DIRS = {".git", ".bon", "node_modules", ".venv", "__pycache__"}


def first_sentence(text: str) -> str:
    """First sentence of a prose line — cut at the first '. ' boundary."""
    text = text.strip()
    idx = text.find(". ")
    if idx != -1:
        return text[: idx + 1]
    return text


def describe(claude_md: Path) -> str:
    """The room's one-liner: first prose line under the H1, as a single sentence.

    Falls back to the H1 heading text, then to '(no description)'.
    """
    heading = ""
    for raw in claude_md.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            if not heading:
                heading = line.lstrip("#").strip()
            continue
        if line.startswith((">", "<!--", "|", "---")):
            continue  # blockquote / status banner / HTML comment / table / rule
        return first_sentence(line)
    return heading or "(no description)"


def find_rooms(repo: Path) -> list[tuple[str, str]]:
    """Every sub-room (dir with a CLAUDE.md), as (relative-path, one-liner).

    The repo-root CLAUDE.md is skipped — it is the orientation doc that hosts
    this index, not a room within it.
    """
    rooms: list[tuple[str, str]] = []
    for claude_md in repo.rglob("CLAUDE.md"):
        rel_parts = claude_md.relative_to(repo).parts
        if any(part in SKIP_DIRS for part in rel_parts):
            continue
        room_dir = claude_md.parent
        if room_dir == repo:
            continue  # repo root — not a sub-room
        rel = room_dir.relative_to(repo).as_posix() + "/"
        rooms.append((rel, describe(claude_md)))
    rooms.sort(key=lambda r: r[0])
    return rooms


def render(repo: Path) -> str:
    rooms = find_rooms(repo)
    lines = [
        MARKER,
        "# Rooms",
        "",
        "An existence index of every room (a directory with a `CLAUDE.md`) in "
        "this repo. Generated — do not hand-edit.",
        "",
    ]
    if rooms:
        for rel, desc in rooms:
            lines.append(f"- [`{rel}`]({rel}CLAUDE.md) — {desc}")
    else:
        lines.append("_No sub-rooms found._")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    check = False
    args = [a for a in argv if a != "--check"]
    if "--check" in argv:
        check = True
    repo = Path(args[0]) if args else Path.cwd()
    repo = repo.resolve()
    if not repo.is_dir():
        print(f"gen-rooms: not a directory: {repo}", file=sys.stderr)
        return 2

    new = render(repo)
    out = repo / "rooms.md"
    current = out.read_text(encoding="utf-8") if out.exists() else None

    if check:
        if current != new:
            print(f"gen-rooms: {out} is stale or missing", file=sys.stderr)
            return 1
        return 0

    if current == new:
        return 0  # no change — leave mtime untouched so nothing churns
    out.write_text(new, encoding="utf-8")
    print(f"gen-rooms: wrote {out} ({new.count(chr(10) + '- ')} rooms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
